export const journeys = {
  catalogue: 'Carregar o catalogo e a identidade do app',
  search: 'Buscar por campeonato ou organizacao',
  noResults: 'Busca sem resultados e recuperacao',
  emptyCatalogue: 'Catalogo vazio',
  apiFallback: 'Catalogo pela API alternativa',
  catalogueOffline: 'Falha das duas APIs do catalogo',
  singleClassification: 'Fase unica de classificacao abre diretamente',
  singleGroups: 'Fase unica de grupos abre diretamente',
  singlePlayoffs: 'Fase unica de playoffs abre diretamente',
  multiplePhases: 'Escolher entre fases de um campeonato',
  cancelPicker: 'Fechar seletor sem navegar',
  noPhases: 'Campeonato sem fases disponiveis',
  unsupportedPhase: 'Ignorar fases nao suportadas',
  entryError: 'Falha ao abrir campeonato e nova tentativa',
  matchDates: 'Consultar partidas e navegar entre datas',
  emptyMatches: 'Fase sem partidas',
  teamLogos: 'Carregar escudos nas tabelas e partidas',
  backNavigation: 'Voltar do campeonato para a busca preservada',
  gamesTab: 'Abrir Meus jogos como visitante',
  auth: 'Entrar pela home e atualizar a sessao',
  authProfile: 'Ver perfil autenticado e sair',
  authGames: 'Ver agenda do atleta autenticado',
  authNavigation: 'Navegar entre entrar cadastro e recuperacao',
  highlights: 'Mostrar destaques do mes sem inventar estatisticas',
  pwaShell: 'Disponibilizar manifest e service worker instalavel',
} as const;
